image: maven:3-jdk-14

stages:
  - build

maven-build:
  stage: build
  script: 
    - cd gr2038/
    - mvn package
    - cat target/site/jacoco/index.html
  artifacts:
    expose_as: 'code coverage'
    paths:
      - gr2038/target/surefire-reports/
      - gr2038/target/site/jacoco/index.html
    reports:
      junit:
        - gr2038/target/surefire-reports/TEST-*.xml
