image: maven:3-jdk-14

stages:
  - verify
  - test

coverage_check:
  image: alpine:latest
  stage: verify
  script:
    - apk add bash
    - apk add jq
    - apk add curl
    
    
testF:
  stage: test
  script:
    - mvn verify
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml