image: maven:3-jdk-14

stages:
  - build
  - test

maven-build:
  stage: build
  script: 
    - cd gr2038/
    - mvn package
    - cat target/site/jacoco/index.html
  artifacts:
    expose_as: 'code coverage'
    paths:
      - target/surefire-reports/
      - target/site/jacoco/index.html
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml

coverage_check:
  image: alpine:latest
  stage: test
  script:
    - apk add bash
    - apk add jq
    - apk add curl
    - bash code-coverage.sh

