image: maven:3-jdk-14

stages:
  - build

core-build:
  stage: build
  script: 
    - cd gr2038/core/
    - mvn package
    - cat target/site/jacoco/index.html
  artifacts:
    expose_as: 'code coverage'
    paths:
      - core/target/surefire-reports/
      - core/target/site/jacoco/index.html
    reports:
      junit:
        - core/target/surefire-reports/TEST-*.xml