stages:
  - build
  - test

build:core:
  image: maven:3-jdk-14
  stage: build
  script:
    - cd gr2038/core/
    - mvn package
    - cat target/site/jacoco/index.html
  artifacts:
    expose_as: "code coverage"
    paths:
      - core/target/surefire-reports/
      - core/target/site/jacoco/index.html
    reports:
      junit:
        - core/target/surefire-reports/TEST-*.xml

build:web:
  image: node:lts
  stage: build
  before_script: []
  script:
    - cd gr2038/ui/
    - npm install
    - npm run build
  artifacts:
    paths:
      - gr2038/ui/node_modules/
      - build

test:web:
  stage: test
  script:
    - cd gr2038/ui/
    - npm run cypress
  needs:
    - job: plan:prod
      artifacts: true
  allow_failure: false
  when: manual
