image: maven:3-jdk-14

stages:
  - build

core-build:
  stage: build
  script: 
    - cd gr2038/
    - mvn package
    - cat core/target/site/jacoco/index.html
  artifacts:
    expose_as: 'code coverage'
    paths:
      - gr2038/core/target/surefire-reports/
      - gr2038/core/target/site/jacoco/index.html
    reports:
      junit:
        - gr2038/core/target/surefire-reports/TEST-*.xml

fxui-build:
  stage: build
  script: 
    - cd gr2038/
    - mvn package
    - cat fxui/target/site/jacoco/index.html
  artifacts:
    expose_as: 'code coverage'
    paths:
      - gr2038/fxui/target/surefire-reports/
      - gr2038/fxui/target/site/jacoco/index.html
    reports:
      junit:
        - gr2038/fxui/target/surefire-reports/TEST-*.xml