stages:
  - build

build:core:
  image: maven:3-jdk-14
  stage: build
  script:
    - cd dinnerium/core/
    - mvn package
    - cat target/site/jacoco/index.html
  artifacts:
    expose_as: "code coverage"
    paths:
      - core/target/surefire-reports/
      - core/target/site/jacoco/index.html
    reports:
      junit:
        - core/target/surefire-reports/TEST-*.xml

build:web:
  image: node:lts
  stage: build
  before_script: []
  script:
    - cd ui/
    - npm install
    - npm run format
    - npm run build
  artifacts:
    paths:
      - ui/node_modules/
      - ui/build/
