@startuml

component core {
	package dinnerium.core
	package dinnerium.json
}

component jackson {
}

dinnerium.json ..> jackson

component fxui {
	package dinnerium.ui
}

dinnerium.ui ..> dinnerium.core
dinnerium.ui ..> dinnerium.json

component javafx {
	component fxml {
	}
}

fxui ..> javafx
fxui ..> fxml

component restapi {
	component Spark {
		package wtf
	}
	package dinnerium.restapi
}

component ui {
	
}


dinnerium.restapi ..> dinnerium.core
dinnerium.restapi ..> dinnerium.json


@enduml