@startuml

component core {
	package simpleex.core
	package simpleex.json
}

component jackson {
}

simpleex.json ..> jackson

component fxui {
	package simpleex.ui
}

simpleex.ui ..> simpleex.core
simpleex.ui ..> simpleex.json

component javafx {
	component fxml {
	}
}

fxui ..> javafx
fxui ..> fxml

component restapi {
	package simpleex.restapi
}

simpleex.restapi ..> simpleex.core
simpleex.restapi ..> simpleex.json

component jaxrs {
}

restapi ..> jaxrs

component restserver {
	package simpleex.restserver
}

simpleex.restserver ..> simpleex.core
simpleex.restserver ..> simpleex.restapi

component jersey {
}

component grizzly2 {
}

restserver ..> jersey
restserver ..> grizzly2

@enduml