@startuml

component core {
	package dinnerium.core
	package dinnerium.json
}

component jackson {
}

dinnerium.json ..> jackson

component fxui {
	package dinnerium.ui
}

dinnerium.ui ..> dinnerium.core
dinnerium.ui ..> dinnerium.json

component javafx {
	component fxml {
	}
}

fxui ..> javafx
fxui ..> fxml

component restapi {
	package dinnerium.server
	package dinnerium.service
}

component spark {
}

component gson {
}

restapi ..> spark
restapi ..> gson

component ui {
	package lol
	package hehe
}


dinnerium.service ..> dinnerium.core
dinnerium.service ..> dinnerium.json


@enduml